version: 0.2

phases:
  install:
    commands:
      - bash -c "$(curl -fsSL https://raw.githubusercontent.com/IN-PART/aws-codebuild-extras/master/install)"
  build:
    commands:
      - # Do nothing
